# Generated by Django 4.2.16 on 2024-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='category',
            field=models.CharField(choices=[('체험', '체험'), ('한잔하솜', '한잔하솜'), ('마켓', '마켓'), ('체험/마켓', '체험/마켓'), ('푸드트럭', '푸드트럭')], max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='booth',
            name='host',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='운영주체'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='가격'),
        ),
    ]
